-- Seeds de parcerias (substitua os UUIDs antes de executar)
-- brand_id e creator_id sao NOT NULL, entao nao podem ser NULL.

-- Troque pelos IDs reais de um brand e de um creator:
-- <BRAND_ID> e <CREATOR_ID>

insert into public.campaigns (
  brand_id,
  creator_id,
  campaign_type,
  compensation_model,
  platform,
  fixed_fee,
  commission_rate,
  products,
  deliverables,
  content_rules,
  proof_required,
  start_date,
  end_date,
  geo_country,
  geo_state,
  geo_cities,
  status,
  inquiry_id
) values
  ('<BRAND_ID>', '<CREATOR_ID>', 'TIKTOK_SHOP_AFFILIATE', 'COMMISSION', 'tiktok', null, 12.5,
   '["https://shop.tiktok.com/item/abc","https://shop.tiktok.com/item/xyz"]'::jsonb,
   '["2 videos shoppable","1 live mention"]'::jsonb,
   'Usar tag #ad e mostrar produto em uso.',
   'Link do video + print do painel do TikTok Shop',
   current_date, current_date + interval '30 days', 'BR', 'SP', '{"Sao Paulo"}', 'active', null),
  ('<BRAND_ID>', '<CREATOR_ID>', 'UGC_FOR_ADS', 'FIXED', 'instagram', 1500.00, null,
   null,
   '["3 videos UGC 20-30s","5 variacoes de hook"]'::jsonb,
   'Evitar linguagem sensivel. Tom leve.',
   'Links dos arquivos finais',
   current_date, current_date + interval '15 days', 'BR', 'RJ', '{"Rio de Janeiro"}', 'draft', null),
  ('<BRAND_ID>', '<CREATOR_ID>', 'SPONSORED_MENTION', 'FIXED', 'youtube', 2000.00, null,
   null,
   '["1 mencao em video","1 story"]'::jsonb,
   'Mencionar beneficio principal no minuto 2.',
   'Link do post/video',
   current_date, current_date + interval '10 days', 'BR', 'MG', '{"Belo Horizonte"}', 'active', null),
  ('<BRAND_ID>', '<CREATOR_ID>', 'SPONSORED_MENTION', 'FIXED', 'tiktok', 900.00, null,
   null,
   '["1 video curto + CTA"]'::jsonb,
   null,
   'Link do post/video',
   current_date, current_date + interval '7 days', 'BR', 'PE', '{"Recife"}', 'delivered', null),
  ('<BRAND_ID>', '<CREATOR_ID>', 'UGC_FOR_ADS', 'FIXED', 'tiktok', 1800.00, null,
   null,
   '["4 videos UGC 15-20s"]'::jsonb,
   'Foco em demonstracao do produto.',
   'Links dos arquivos finais',
   current_date, current_date + interval '20 days', 'BR', 'BA', '{"Salvador"}', 'active', null),
  ('<BRAND_ID>', '<CREATOR_ID>', 'TIKTOK_SHOP_AFFILIATE', 'COMMISSION', 'tiktok', null, 8.0,
   '["https://shop.tiktok.com/item/123"]'::jsonb,
   '["3 videos shoppable"]'::jsonb,
   null,
   'Link do video + print do painel do TikTok Shop',
   current_date, current_date + interval '25 days', 'BR', 'PR', '{"Curitiba"}', 'draft', null),
  ('<BRAND_ID>', '<CREATOR_ID>', 'SPONSORED_MENTION', 'FIXED', 'instagram', 1200.00, null,
   null,
   '["1 post feed + 2 stories"]'::jsonb,
   'Usar hashtag #publi.',
   'Link do post/video',
   current_date, current_date + interval '12 days', 'BR', 'RS', '{"Porto Alegre"}', 'closed', null),
  ('<BRAND_ID>', '<CREATOR_ID>', 'UGC_FOR_ADS', 'FIXED', 'youtube', 2500.00, null,
   null,
   '["2 videos UGC 30s"]'::jsonb,
   'Conteudo com tom explicativo.',
   'Links dos arquivos finais',
   current_date, current_date + interval '18 days', 'BR', 'DF', '{"Brasilia"}', 'active', null),
  ('<BRAND_ID>', '<CREATOR_ID>', 'SPONSORED_MENTION', 'FIXED', 'instagram', 800.00, null,
   null,
   '["1 mencao em reels"]'::jsonb,
   null,
   'Link do post/video',
   current_date, current_date + interval '5 days', 'BR', 'CE', '{"Fortaleza"}', 'active', null),
  ('<BRAND_ID>', '<CREATOR_ID>', 'TIKTOK_SHOP_AFFILIATE', 'COMMISSION', 'tiktok', null, 15.0,
   '["https://shop.tiktok.com/item/999"]'::jsonb,
   '["1 live mention"]'::jsonb,
   'Apresentar beneficios e desconto.',
   'Link do video + print do painel do TikTok Shop',
   current_date, current_date + interval '14 days', 'BR', 'SC', '{"Florianopolis"}', 'active', null);
